### ISSUE TITLE
image tomyhero/sensu:latest not found

### ISSUE THREAD

**Issue by AGovorukha** [tomyhero/docker-sensu#1]
Hello,

I've got errors when I run `docker build -t tomyhero/sensu .`
Can't download any sensu plugins from
[https://raw.githubusercontent.com/sensu/sensu-community-plugins/master/plugins/system/](url)
Got `ERROR 404: Not Found.`

Where can I get this plugins?
Could you please help?

**Comment by tomyhero** [comment]
sorry for late replay,

they change url to here

https://github.com/sensu-plugins

so you need to find in there.

 I may fix Dockerfile someday when i have time.
